sudo: false
dist: trusty

language: elixir
elixir:
  - '1.5.3'
  - '1.6.6'
  - '1.7.3'

otp_release:
  - '20.3.8'
  - '21.0.1'

matrix:
  exclude:
    - elixir: '1.5.3'
      otp_release: '21.0.1'

env:
  - MIX_ENV=test

cache:
  directories:
    - $HOME/.mix
    - deps
    - _build

script:
  - mix credo --strict
  - mix dialyzer
